# -*- coding: utf-8 -*-
"""
Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s1ZQBfgNq6qoo2JtubaXIf_CyRNu76vY

# Training a ML model using CICIoT2023

This notebook shows how an LR, KNN, RF, DT, lightGBM, and xgBoost model can be trained using the CICIoT2023 CSV files.


Benign' to 0 and 'Attack' to 1.

=====
Here, We applied SMOTE
"""

!rm -rf /content/*

#cell 0
!pip install lightgbm xgboost

#cell 1 Imports + إعدادات عامة
import pandas as pd
import numpy as np

from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score, accuracy_score, precision_score, recall_score, f1_score

from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier

from xgboost import XGBClassifier
from lightgbm import LGBMClassifier

from imblearn.over_sampling import SMOTE
from imblearn.pipeline import Pipeline as ImbPipeline

from sklearn.ensemble import VotingClassifier, StackingClassifier

from tqdm.auto import tqdm

RANDOM_STATE = 42

"""### Importing Dataset"""

#cell 2
from google.colab import files

print(" ارفع ملف kaggle.json (من حسابك في Kaggle)")
files.upload()  # اختاري kaggle.json

#cell 3
!mkdir -p ~/.kaggle
!mv kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

#cell 4
# KAGGLE_DATASET = "gp1f9imamu/small-sample-to-testcode"
KAGGLE_DATASET = "gp1f9imamu/ciciot2023-samblef"

!kaggle datasets download -d $KAGGLE_DATASET -p /content
!ls -lh /content

#cell 5

# !unzip -o /content/small-sample-to-testcode.zip -d /content
# !ls -lh /content

#cell 5

!unzip -o /content/ciciot2023-samblef.zip -d /content
!ls -lh /content

#cell 6
import pandas as pd

# تحميل بيانات train و test
train = pd.read_csv("/content/train.csv")
test  = pd.read_csv("/content/test.csv")

print(train.columns)  # بس للتأكيد

# هنا نحدد عمود اللابل الصحيح
y_train = train["label"]
X_train = train.drop(columns=["label"])

y_test = test["label"]
X_test = test.drop(columns=["label"])

print("✅ X_train shape:", X_train.shape)
print("✅ y_train shape:", y_train.shape)
print("✅ X_test shape:", X_test.shape)
print("✅ y_test shape:", y_test.shape)

print("\nتوزيع اللابل في train:")
print(y_train.value_counts())

print("\nتوزيع اللابل في test:")
print(y_test.value_counts())

"""### Scaling"""

from sklearn.preprocessing import StandardScaler

#cell 5

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled  = scaler.transform(X_test)

print("✅ Scaling done")

#cell 6

import os
import numpy as np
import pandas as pd
from datetime import datetime

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.metrics import confusion_matrix

from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier


# مجلد لحفظ النتائج (جداول + صور)
RESULTS_DIR = "/content/results"
os.makedirs(RESULTS_DIR, exist_ok=True)

# تايم ستامب للملفات
TIMESTAMP = datetime.now().strftime("%Y%m%d_%H%M")


def get_models():
    return {
        "KNN": KNeighborsClassifier(n_neighbors=7, n_jobs=-1),
        "RandomForest": RandomForestClassifier(
            n_estimators=200,
            random_state=42,
            n_jobs=-1
        ),
        "XGBoost": XGBClassifier(
            n_estimators=300,
            max_depth=6,
            learning_rate=0.1,
            subsample=0.8,
            colsample_bytree=0.8,
            random_state=42,
            n_jobs=-1,
            eval_metric="logloss"
        ),
        "LightGBM": LGBMClassifier(
            n_estimators=400,
            learning_rate=0.05,
            random_state=42,
            n_jobs=-1
        ),
        "DecisionTree": DecisionTreeClassifier(random_state=42),
    }


def compute_metrics(y_true, y_pred):
    cm = confusion_matrix(y_true, y_pred)
    TN, FP, FN, TP = cm.ravel()
    total = TN + FP + FN + TP

    acc = (TP + TN) / total

    # Benign (class 0)
    recall_0 = TN / (TN + FP) if (TN + FP) else 0
    precision_0 = TN / (TN + FN) if (TN + FN) else 0
    f1_0 = 2 * precision_0 * recall_0 / (precision_0 + recall_0) if (precision_0 + recall_0) else 0

    # Attack (class 1)
    recall_1 = TP / (TP + FN) if (TP + FN) else 0
    precision_1 = TP / (TP + FP) if (TP + FP) else 0
    f1_1 = 2 * precision_1 * recall_1 / (precision_1 + recall_1) if (precision_1 + recall_1) else 0

    # Macro Average
    precision_macro = (precision_0 + precision_1) / 2
    recall_macro    = (recall_0 + recall_1) / 2
    f1_macro        = (f1_0 + f1_1) / 2

    return {
        "Accuracy": acc,

        "Precision_Benign": precision_0,
        "Recall_Benign": recall_0,
        "F1_Benign": f1_0,

        "Precision_Attack": precision_1,
        "Recall_Attack": recall_1,
        "F1_Attack": f1_1,

        "Precision_Macro": precision_macro,
        "Recall_Macro": recall_macro,
        "F1_Macro": f1_macro,

        "TN": TN, "FP": FP, "FN": FN, "TP": TP,
        "CM": cm,
    }


def save_confusion_matrix_png(cm, title, fname):
    plt.figure(figsize=(4, 3))
    sns.heatmap(cm, annot=True, fmt="d", cmap="Blues")
    plt.title(title)
    plt.xlabel("Predicted")
    plt.ylabel("Actual")
    plt.tight_layout()

    path = os.path.join(RESULTS_DIR, fname)
    plt.savefig(path, dpi=200)
    plt.close()
    return path

#cell 7

baseline_models = get_models()

for name, model in baseline_models.items():
    model.fit(X_train_scaled, y_train)

print("✅ Baseline training done")

#cell 8

baseline_results = []

for name, model in baseline_models.items():
    y_pred = model.predict(X_test_scaled)
    m = compute_metrics(y_test, y_pred)

    img = save_confusion_matrix_png(
        m["CM"],
        f"{name} - Baseline",
        f"{name}_baseline_{TIMESTAMP}.png"
    )

    baseline_results.append({
        "Model": name,
        "Phase": "Baseline",

        "Accuracy": round(m["Accuracy"] * 100, 2),

        "Precision_Benign": round(m["Precision_Benign"] * 100, 2),
        "Recall_Benign": round(m["Recall_Benign"] * 100, 2),
        "F1_Benign": round(m["F1_Benign"] * 100, 2),

        "Precision_Attack": round(m["Precision_Attack"] * 100, 2),
        "Recall_Attack": round(m["Recall_Attack"] * 100, 2),
        "F1_Attack": round(m["F1_Attack"] * 100, 2),

        "Precision_Macro": round(m["Precision_Macro"] * 100, 2),
        "Recall_Macro": round(m["Recall_Macro"] * 100, 2),
        "F1_Macro": round(m["F1_Macro"] * 100, 2),

        "TN": m["TN"], "FP": m["FP"], "FN": m["FN"], "TP": m["TP"],
        "CM_png": img,
    })

baseline_df = pd.DataFrame(baseline_results)
display(baseline_df)

baseline_file = os.path.join(RESULTS_DIR, f"baseline_results_{TIMESTAMP}.csv")
baseline_df.to_csv(baseline_file, index=False)
print("✅ Baseline saved to:", baseline_file)

"""# **WITH SMOTE**"""

#cell 9

from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=42)
X_train_sm, y_train_sm = smote.fit_resample(X_train_scaled, y_train)

print("قبل SMOTE:", dict(y_train.value_counts()))
print("بعد  SMOTE:", dict(y_train_sm.value_counts()))

smote_models = get_models()

for name, model in smote_models.items():
    model.fit(X_train_sm, y_train_sm)

print("✅ SMOTE training done")

#cell 10

smote_results = []

for name, model in smote_models.items():
    y_pred = model.predict(X_test_scaled)
    m = compute_metrics(y_test, y_pred)

    img = save_confusion_matrix_png(
        m["CM"],
        f"{name} - SMOTE",
        f"{name}_smote_{TIMESTAMP}.png"
    )

    smote_results.append({
        "Model": name,
        "Phase": "SMOTE",

        "Accuracy": round(m["Accuracy"] * 100, 2),

        "Precision_Benign": round(m["Precision_Benign"] * 100, 2),
        "Recall_Benign": round(m["Recall_Benign"] * 100, 2),
        "F1_Benign": round(m["F1_Benign"] * 100, 2),

        "Precision_Attack": round(m["Precision_Attack"] * 100, 2),
        "Recall_Attack": round(m["Recall_Attack"] * 100, 2),
        "F1_Attack": round(m["F1_Attack"] * 100, 2),

        "Precision_Macro": round(m["Precision_Macro"] * 100, 2),
        "Recall_Macro": round(m["Recall_Macro"] * 100, 2),
        "F1_Macro": round(m["F1_Macro"] * 100, 2),

        "TN": m["TN"], "FP": m["FP"], "FN": m["FN"], "TP": m["TP"],
        "CM_png": img,
    })

smote_df = pd.DataFrame(smote_results)
display(smote_df)

smote_file = os.path.join(RESULTS_DIR, f"smote_results_{TIMESTAMP}.csv")
smote_df.to_csv(smote_file, index=False)
print("✅ SMOTE saved to:", smote_file)

"""# **Hyperparameter Tuning**"""

from sklearn.model_selection import train_test_split

MAX_TUNING_SAMPLES = 30000

if len(X_train) <= MAX_TUNING_SAMPLES:
    X_train_tune = X_train.copy()
    y_train_tune = y_train.copy()
else:
    X_train_tune, _, y_train_tune, _ = train_test_split(
        X_train,
        y_train,
        train_size=MAX_TUNING_SAMPLES,
        stratify=y_train,
        random_state=42
    )

print("📊 كامل بيانات التدريب:", len(X_train))
print("📊 حجم عينة التونينق:", len(X_train_tune))
print("توزيع اللابل:")
print(y_train_tune.value_counts())

from sklearn.model_selection import StratifiedKFold
from imblearn.pipeline import Pipeline as ImbPipeline
from imblearn.over_sampling import SMOTE

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

models_pipelines = {
    "KNN": ImbPipeline([
        ("scaler", StandardScaler()),
        ("smote", SMOTE(random_state=42)),
        ("clf", KNeighborsClassifier())
    ]),
    "DecisionTree": ImbPipeline([
        ("scaler", StandardScaler()),
        ("smote", SMOTE(random_state=42)),
        ("clf", DecisionTreeClassifier(random_state=42))
    ]),
    "RandomForest": ImbPipeline([
        ("scaler", StandardScaler()),
        ("smote", SMOTE(random_state=42)),
        ("clf", RandomForestClassifier(n_jobs=-1, random_state=42))
    ]),
    "XGBoost": ImbPipeline([
        ("scaler", StandardScaler()),
        ("smote", SMOTE(random_state=42)),
        ("clf", XGBClassifier(tree_method="hist", eval_metric="logloss", random_state=42, n_jobs=-1))
    ]),

}

print("✅ Pipelines جاهزة")

param_distributions = {
    "KNN": {
        "clf__n_neighbors": [3,5,7,9],
        "clf__weights": ["uniform","distance"],
        "clf__p": [1,2]
    },
    "DecisionTree": {
        "clf__criterion": ["gini","entropy"],
        "clf__max_depth": [None,10,20],
        "clf__min_samples_split": [2,5],
        "clf__min_samples_leaf": [1,2]
    },
    "RandomForest": {
        "clf__n_estimators": [100,200],
        "clf__max_depth": [None,20],
        "clf__min_samples_split": [2,5],
        "clf__min_samples_leaf": [1,2],
        "clf__max_features": ["sqrt","log2"]
    },
    "XGBoost": {
        "clf__n_estimators": [100,200],
        "clf__learning_rate": [0.05,0.1],
        "clf__max_depth": [3,5],
        "clf__subsample": [0.8,1.0],
        "clf__colsample_bytree": [0.8,1.0],
        "clf__gamma": [0,0.1],
        "clf__reg_lambda": [1,5]
    },

}

from sklearn.model_selection import RandomizedSearchCV
import time

best_models = {}
best_params_list = []

print("🚀 بدء التونينق")

for model_name, pipeline in models_pipelines.items():

    search = RandomizedSearchCV(
        pipeline,
        param_distributions[model_name],
        n_iter=10,
        scoring="f1_macro",
        cv=cv,
        n_jobs=-1,
        verbose=1,
        random_state=42,
        refit=True
    )

    start = time.time()
    search.fit(X_train_tune, y_train_tune)

    best_model = search.best_estimator_
    best_model.fit(X_train, y_train)
    best_models[model_name] = best_model

    row = {"model": model_name, "best_cv_f1": search.best_score_}
    row.update(search.best_params_)
    best_params_list.append(row)

    print(f"{model_name} finished | F1 = {round(search.best_score_,4)}")

print(" انتهى التونينق")

from sklearn.metrics import confusion_matrix
import pandas as pd

print("📏 بدء تقييم النماذج بعد التونينق...\n")

tuned_results = []

for i, (model_name, best_model) in enumerate(best_models.items(), start=1):
    print(f"Evaluation {i}/{len(best_models)}: {model_name}")

    # التنبؤ على test
    y_pred = best_model.predict(X_test)

    # حساب جميع المقاييس
    m = compute_metrics(y_test, y_pred)

    # حفظ صورة مصفوفة الالتباس
    cm_title = f"{model_name} - Tuned"
    cm_filename = f"{model_name}_tuned_{TIMESTAMP}.png"
    cm_path = save_confusion_matrix_png(m["CM"], cm_title, cm_filename)

    # تخزين النتائج كاملة
    tuned_results.append({
        "Model": model_name,

        "Accuracy": round(m["Accuracy"] * 100, 2),

        "Precision_Benign": round(m["Precision_Benign"] * 100, 2),
        "Recall_Benign":    round(m["Recall_Benign"] * 100, 2),
        "F1_Benign":        round(m["F1_Benign"] * 100, 2),

        "Precision_Attack": round(m["Precision_Attack"] * 100, 2),
        "Recall_Attack":    round(m["Recall_Attack"] * 100, 2),
        "F1_Attack":        round(m["F1_Attack"] * 100, 2),

        "Precision_Macro": round(m["Precision_Macro"] * 100, 2),
        "Recall_Macro":    round(m["Recall_Macro"] * 100, 2),
        "F1_Macro":        round(m["F1_Macro"] * 100, 2),

        "TN": m["TN"],
        "FP": m["FP"],
        "FN": m["FN"],
        "TP": m["TP"],

        "cm_path": cm_path
    })

print("\n✅ انتهت مرحلة تقييم النماذج بعد التونينق.")

# تحويل النتائج إلى DataFrame
tuned_df = pd.DataFrame(tuned_results)
display(tuned_df)


TUNING_RESULTS_CSV = os.path.join(RESULTS_DIR, f"tuned_results_{TIMESTAMP}.csv")
tuned_df.to_csv(TUNING_RESULTS_CSV, index=False)

print(f"\n✓ تم حفظ نتائج التونينق في: {TUNING_RESULTS_CSV}")

tuned_df["macro_f1"] = tuned_df["F1_Macro"]
top_models = tuned_df.sort_values("macro_f1", ascending=False)["Model"][:3]

print("أفضل النماذج:", list(top_models))
base_estimators = [(m, best_models[m]) for m in top_models]

"""# Ensemble"""

from sklearn.ensemble import VotingClassifier, StackingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
import pandas as pd
import os

ensemble_results = []

print("اختيار أفضل النماذج من مرحلة الهايبر لاستخدامها في الـ Ensemble...\n")

# نرتب حسب macro_f1 تنازليًا
tuned_sorted = tuned_df.sort_values(by="macro_f1", ascending=False)

# نحدد عدد النماذج اللي بنستخدمها في الـ Ensemble (مثلاً أفضل 3)
top_n = 3
top_models_names = tuned_sorted["Model"].unique()[:top_n]

print("أفضل النماذج المستخدمة في الـ Ensemble:")
for name in top_models_names:
    print("-", name)

# نكوّن قائمة (اسم, موديل) لاستخدامها في Voting/Stacking
base_estimators = [(name, best_models[name]) for name in top_models_names]

"""# HARD & SOFT VOTING"""

from sklearn.ensemble import VotingClassifier

voting_soft = VotingClassifier(estimators=base_estimators, voting="soft", n_jobs=-1)
voting_hard = VotingClassifier(estimators=base_estimators, voting="hard", n_jobs=-1)

voting_soft.fit(X_train, y_train)
voting_hard.fit(X_train, y_train)

print("✅ Voting trained")

"""# STAKING"""

from sklearn.ensemble import StackingClassifier
from sklearn.linear_model import LogisticRegression

stacking = StackingClassifier(
    estimators=base_estimators,
    final_estimator=LogisticRegression(max_iter=1000,class_weight="balanced"),
    cv=cv,
    n_jobs=-1
)

stacking.fit(X_train, y_train)
print("✅ Stacking trained")

"""# Ensemble (Soft + Hard + Stacking) test&Results"""

from sklearn.metrics import confusion_matrix
import pandas as pd

print("\n📏 بدء تقييم نماذج الـ Ensemble...\n")

ensemble_results = []

ensembles = [
    ("Voting_Soft", voting_soft),
    ("Voting_Hard", voting_hard),
    ("Stacking", stacking),
]

for name, model in ensembles:
    print(f"Evaluating: {name}")

    y_pred = model.predict(X_test)
    m = compute_metrics(y_test, y_pred)

    cm_title = f"{name} - Ensemble"
    cm_filename = f"{name}_ensemble_{TIMESTAMP}.png"
    cm_path = save_confusion_matrix_png(m["CM"], cm_title, cm_filename)

    ensemble_results.append({
        "Model": name,

        "Accuracy": round(m["Accuracy"] * 100, 2),

        "Precision_Benign": round(m["Precision_Benign"] * 100, 2),
        "Recall_Benign":    round(m["Recall_Benign"] * 100, 2),
        "F1_Benign":        round(m["F1_Benign"] * 100, 2),

        "Precision_Attack": round(m["Precision_Attack"] * 100, 2),
        "Recall_Attack":    round(m["Recall_Attack"] * 100, 2),
        "F1_Attack":        round(m["F1_Attack"] * 100, 2),

        "Precision_Macro": round(m["Precision_Macro"] * 100, 2),
        "Recall_Macro":    round(m["Recall_Macro"] * 100, 2),
        "F1_Macro":        round(m["F1_Macro"] * 100, 2),

        "TN": m["TN"],
        "FP": m["FP"],
        "FN": m["FN"],
        "TP": m["TP"],

        "cm_path": cm_path
    })

print("\n✅ انتهى تقييم الـ Ensemble.")

ensemble_df = pd.DataFrame(ensemble_results)
display(ensemble_df)

ENSEMBLE_RESULTS_CSV = os.path.join(RESULTS_DIR, f"ensemble_results_{TIMESTAMP}.csv")
ensemble_df.to_csv(ENSEMBLE_RESULTS_CSV, index=False)

print(f"\n✓ تم حفظ نتائج الـ Ensemble في: {ENSEMBLE_RESULTS_CSV}")

import shutil
import os

# اسم المجلد المراد ضغطه
folder_name = "results"

# اسم الملف المضغوط الناتج
zip_name = "results_backup"

# إنشاء ملف ZIP
shutil.make_archive(zip_name, 'zip', folder_name)

# طباعة المسار للتأكد
zip_path = os.path.abspath(zip_name + ".zip")
print("تم إنشاء الملف المضغوط بنجاح ✅")
print("المسار:", zip_path)

# محاولة تنزيله تلقائيًا (إذا كنت على Google Colab)
try:
    from google.colab import files
    files.download(zip_path)
except:
    print("إذا لم يبدأ التحميل تلقائيًا، انسخ المسار أعلاه ونزّله يدويًا من مدير الملفات.")
